### ISSUE TITLE
Link to Matt Dray's 2020-01-30 talk at the Bioinformatics London Meetup

### ISSUE THREAD

**Issue by wlandau** [ropensci-books/drake#146]
Is this alright with you, @matt-dray? I keep a record of presentations at https://books.ropensci.org/drake/index.html#presentations.

**Comment by wlandau** [comment]
For my reference: https://github.com/matt-dray/drake-bioinformatics, https://matt-dray.github.io/drake-bioinformatics/. Related: #132.

**Comment by matt-dray** [comment]
Of course, by all means.

**Comment by wlandau** [comment]
Awesome, thanks!
