### ISSUE TITLE
Shiny App not working

### ISSUE THREAD

**Issue by duju211** [ropensci-books/drake#147]
The shiny app (https://wlandau.shinyapps.io/learndrakeplans/) linked at the beginning of Chapter 5 'Static branching' throws the following error:

![image](https://user-images.githubusercontent.com/13487201/73737415-e5616380-4742-11ea-9618-c123be63a93f.png)

**Comment by wlandau** [comment]
Thanks for letting me know. The issue was caused by https://github.com/ropensci/drake/issues/1156. Redeploying now.

For future reference, the development repository of that app is https://github.com/wlandau/learndrake.

**Comment by wlandau** [comment]
Fixed.
