### ISSUE TITLE
Section 13.4: Predict runtime sec needs a revision

### ISSUE THREAD

**Issue by pat-s** [ropensci-books/drake#152]
Section "Strategize your high-performance computing": Some warnings in the code output and the plot shows a horizontal line only: https://books.ropensci.org/drake/time.html

**Comment by wlandau** [comment]
Thanks, Pat. The `jobs` argument of `predict_runtime()` changed to `jobs_predict` in https://github.com/ropensci/drake/pull/1123. Now fixed. Travis should deploy it soon.
