### ISSUE TITLE
Custom concatenation of sub-targets in dynamic plan

### ISSUE THREAD

**Issue by adamaltmejd** [ropensci-books/drake#155]
Testing out a dynamic plan for a project where some targets have format "fst_dt". `vec_c` concatenates to a single data.frames which is not what I want. I would prefer to just get a list of subtargets like one would get with static branching and `transform = combine()`, but `dynamic = group()` does not seem to work this way.

This works as intended:
```
s_plan <- drake_plan(
    dts = target(data.table(a = a, b = c(4)), transform = map(a = c(1,2,3)), format = "fst_dt"),
    final = target(rbindlist(list(dts)), transform = combine(dts), format = "fst_dt")
)
```

But not sure how to reproduce with dynamic targets, the following code throws an vctrs error `vctrs methods must be implemented for class drake_format_fst_dt`. For my use case, ideally `readd(dts)` would just give me a list of data.tables whenever vec_c can't concatenate without losing data. But understand if that would be confusing. Perhaps just allow an option in target() to disable concatenation?

```
d_plan <- drake_plan(
    a = c(1,2,3),
    dts = target(data.table(a = a, b = c(4)), dynamic = map(a = a), format = "fst_dt"),
    final = target(rbindlist(list(dts)), dynamic = group(dts), format = "fst_dt")
)
```

**Comment by wlandau** [comment]
In dynamic branching, unless you are grouping by a factor, you don't actually need `group()`. Aggregation happens automatically through `vctrs`, but it gets tricky because of https://github.com/r-lib/vctrs/issues/694, so you will need to coerce the aggregate to a `data.table` at the end.

``` r
library(data.table)
library(drake)

plan <- drake_plan(
  a = c(1, 2, 3),
  dts = target(
    data.table(a = a, b = 4),
    dynamic = map(a = a),
    format = "fst_dt"
  ),
  final = target(
    as.data.table(dts),
    format = "fst_dt"
  )
)

make(plan)
#> ▶ target a
#> ▶ dynamic dts
#> > subtarget dts_0a25b599
#> > subtarget dts_6aab08ab
#> > subtarget dts_a150a51a
#> ■ finalize dts
#> ▶ target final

loadd(final)

final
#>    a b
#> 1: 1 4
#> 2: 2 4
#> 3: 3 4

is.data.table(final)
#> [1] TRUE
```

<sup>Created on 2020-04-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by adamaltmejd** [comment]
Thanks!

Doesn't this work by first using vec_c to concat the data tables from dts to a data frame and then convert it to a data.table at the end? So it would still lose all data.table properties (like key) and not work with list variables?

**Comment by wlandau** [comment]
It does, and it will until https://github.com/r-lib/vctrs/issues/694 is fixed. To work around it, you could do something like this:

```{r}
plan <- drake_plan(
  a = c(1, 2, 3),
  dts = target(
    list(data.table(a = a, b = 4)), # Wrap small data.tables in lists.
    dynamic = map(a = a),
    format = "qs" # Alternative to fst_dt
  ),
  final = target(
    as.data.table(rbindlist(dts)),
    format = "fst_dt"
  )
)
```

**Comment by adamaltmejd** [comment]
Gotcha. Makes sense to fix this in vctrs instead. Thanks for the workaround!
