### ISSUE TITLE
Replace make() with r_make() in the manual

### ISSUE THREAD

**Issue by wlandau** [ropensci-books/drake#160]
Related: https://github.com/ropensci/drake/issues/1281. r_make() is more reproducible, and it creates a more consistent user experience.

**Comment by vkehayas** [comment]
I appreciate the push towards reproducibility behind this move although I never use `r_make` and friends as I always run `make` in a fresh session. If `r_make` is going to become the default and `make` to be deprecated, as I understand this proposal, may I humbly ask to drop the requirement to also run `drake_config` inside _drake.R? It's not too much trouble for me the user to also add that line --it's just that I view this as a pre-processing step that the end-user does not need to have access to. Put in another way --and please correct me if I am wrong-- I have not found a reason why `drake_config` and `make` should be run with different parameters for the same plan. If that's true, this issue marks a great occasion to completely hide `drake_config` from the user. 

Related:  
https://github.com/ropensci/drake/issues/1118
https://github.com/ropensci/drake/pull/1123

**Comment by vkehayas** [comment]
Although my previous comment could still stand for the main repository, I now see that we are in the manual's repository and I got over-excited! Apologies...

**Comment by wlandau** [comment]
Thanks for the feedback.

>  If r_make is going to become the default and make to be deprecated, as I understand this proposal

Sorry, that's not what I intended to say. I just meant that we should predominantly use `r_make()` in the manual and examples. `make()` will not be deprecated. 

> may I humbly ask to drop the requirement to also run drake_config inside _drake.R?

I see your point, but I think `drake_config()` actually plays a useful role here. `_drake.R` not only powers `r_make()`, but also utilities like `r_vis_drake_graph()` and `r_outdated()`. And `drake_config()` not only accepts the plan, but also the cache, the seed, the trigger, and other arguments that need to stay consistent across all utility functions. With those arguments are scripted in `_drake.R`, there is less room to mess up an argument as users transition from inspecting the pipeline to running it seriously.

**Comment by wlandau** [comment]
Rethinking this. @vkehayas, you make a good point about `drake_config()`. It's a funny preprocessing step that is difficult for users to understand. It would probably muddy the waters to use it instead of `make()` everywhere.
