### ISSUE TITLE
FAQ is empty

### ISSUE THREAD

**Issue by smingerson** [ropensci-books/drake#161]
I went to check the [FAQ](https://books.ropensci.org/drake/faq.html) and it was blank. If I click the "issues tagged on Github" link, that also shows up empty. It looks like the label to look for needs to be "type: faq" instead of "frequently asked question".

Edit: It looks like the code to build the FAQ checks for the label the repo uses (type: faq), but the GitHub link at the top of the page needs to be updated. Now I am not sure why it is blank.

**Comment by wlandau** [comment]
Thanks, it's back up now.
