### ISSUE TITLE
Search bar broken

### ISSUE THREAD

**Issue by malcolmbarrett** [ropensci-books/drake#165]
Hi -- thanks for this great resource!

On Chrome and Safari, the search bar does not work (it doesn't appear when clicking). I have seen this on two separate Macs. I haven't been able to replicate this in other bookdown sites, so I think it may be something about the configuration for this site, and I wanted to bring it to your attention. Thanks!

**Comment by wlandau** [comment]
Maybe it's an issue with the latest `bookdown`? The search bar does not work for me either, but neither does a clone of https://github.com/yihui/bookdown-minimal when I render locally and view in a browser. Would you install `bookdown` 0.20, render https://github.com/yihui/bookdown-minimal with `bookdown::render_book('index.Rmd', 'all')`, open `_book/index.html` in a browser, and try the search bar there?

**Comment by wlandau** [comment]
When I build and serve the manual locally with 

```r
source("faq.R")
source("build.R")
servr::httw(".", site.dir = "_book")
```

then the search bar works. On the `gh-pages` branch I see the usual search bar JS and CSS code makes it into https://github.com/ropensci-books/drake/tree/gh-pages/libs/gitbook-2.6.7. For the website itself, the only messages in the browser's developer console are about Google Analytics cookies.

In other words, I do not know how to debug this, and I will need the help of a PR or someone who is more experienced in web development.

**Comment by malcolmbarrett** [comment]
I'm having basically the same results. I see that other rOpenSci books are ok (e.g. https://books.ropensci.org/fulltext), so it's not simply an issue of using GH pages...

**Comment by wlandau** [comment]
Now fixed. Details at https://github.com/rstudio/bookdown-demo/issues/12#issuecomment-657329216.

**Comment by malcolmbarrett** [comment]
Wow, this is some serious detective work. Nice job and thanks for fixing!
