### ISSUE TITLE
Links to "#packages" going to the wrong part of book

### ISSUE THREAD

**Issue by malcolmbarrett** [ropensci-books/drake#166]
Links to the packages example in chapter 11 are broken throughout the book. Instead of going to chapter 11, it takes you to chapter 9, under the "Package" heading.

For example, in the book index menu, clicking on Chapter 11 brings you to that place in Chapter 9, as does the link to Chapter 11 at the bottom of Chapter 19, here: https://books.ropensci.org/drake/triggers.html#a-more-practical-example

I believe this is happening because of this line: https://github.com/ropensci-books/drake/blob/6fc694fa098435a0343e32f085fbaff6854a4d2e/packages.Rmd#L1

In Chapter 9, `# Packages` also has that ID (it's just not explicitly set), which occurs before chapter 11 in the aggregated Rmd file that bookdown makes before knitting.  I *think* changing the ID in Chapter 11 to something like `{packages-example}` will fix the issue, but I have not confirmed because I'm a little daunted to try to build this book locally.

**Comment by wlandau-lilly** [comment]
Thanks, should be fixed once the manual rebuilds.
