### ISSUE TITLE
Include/embed Miles' NYC R Meetup talk

### ISSUE THREAD

**Issue by wlandau** [ropensci-books/drake#167]
I would like to mention https://github.com/MilesMcBain/nycr_meetup_talk at [here](https://github.com/ropensci-books/drake/blob/4c8c60401d56b253e88e4ff7d8b6e1fb416be22d/index.Rmd#L279-L298) and embed the video [here](https://github.com/ropensci-books/drake/blob/4c8c60401d56b253e88e4ff7d8b6e1fb416be22d/index.Rmd#L36-L38) and [here](https://github.com/ropensci/drake/blob/70dbce5fd31b4578207571bfc2907c94acb38bc7/README.Rmd#L112-L121). @MilesMcBain, do I have your permission? It was such an insightful presentation, and it improved the way I think about workflows.

**Comment by MilesMcBain** [comment]
Thanks Will! Permission granted. I don't know that permission can actually account for the video, since I don't really know what the copyright status of that work would be.

**Comment by MilesMcBain** [comment]
(It should be fine though)

**Comment by wlandau** [comment]
Thanks, Miles! I added a [note in the `COPYRIGHT` file](https://github.com/ropensci-books/drake/blob/daef2ea10a2562525c4a795937f7038a830a3057/COPYRIGHT#L2) just to be safe.
